[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "poe-search"
version = "1.3.0"
description = "Poe Search GUI"
dependencies = ["PyQt6", "selenium", "requests"]

[tool.setuptools.packages.find]
where = ["src"]
