site_name: Poe Search
site_description: A tool for searching and organizing Poe.com conversations
site_url: https://github.com/kevin/poe-search
repo_url: https://github.com/kevin/poe-search
repo_name: kevin/poe-search

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Configuration: configuration.md
  - User Guide:
    - CLI Usage: cli.md
    - Python API: api.md
    - Search Features: search.md
    - Export Options: export.md
  - Advanced:
    - Database Schema: database.md
    - Extending: extending.md
    - Troubleshooting: troubleshooting.md
  - Development:
    - Contributing: contributing.md
    - Development Setup: development.md
    - API Reference: reference/
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kevin/poe-search
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/poe-search/
